apiVersion: v1
kind: Service
metadata:
  name: savsmith-final-redis-service
  labels:
    username: savsmith
    env: test
spec:
  type: ClusterIP
  selector:
    app: savsmith-final-redis
  ports:
  - name: final-redis
    port: 6379
    targetPort: 6379
