apiVersion: v1
kind: Service
metadata:
  name: savsmith-final-flask-service
  labels:
    username: savsmith
    env: test
spec:
  type: ClusterIP
  selector:
    app: savsmith-final-flask
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000
